### ISSUE TITLE
Feature request - array of rigid body markers

### ISSUE THREAD

**Issue by SamDSchofield** [mje-nz/natnet_ros#1]
It would be great if there were a topic for each rigid body that published an array of the positions of all the markers in that rigid body.

At the moment to get all the markers for a rigid body, I have to iterate over all the marker topics for the rigid body and add them to a TimeSynchronizer message filter.

**Comment by mje-nz** [comment]
Thanks for the request, would you mind testing the markerlist-topic branch?

**Comment by SamDSchofield** [comment]
Perfect. Thanks!
