### ISSUE TITLE
 Fixed Frame [map] does not exist

### ISSUE THREAD

**Issue by knightsamar** [mje-nz/natnet_ros#9]
**Environment**
Motive version: 2.1.1
ROS distribution: Kinetic
Operating system: Ubuntu 16.04.6
Python version: 2.7.12

**`natnet_ros` version**
![Screenshot from 2019-09-04 17-39-04](https://user-images.githubusercontent.com/230170/64304658-83a58f00-cf41-11e9-9a08-4122c85d8cf8.png)

`natnet_ros` branch: dev
`natnet_ros` commit: 94127eb
`python_natnet` branch: dev
`python_natnet` commit: 0aecc86 

**Describe the bug**
When trying to visualize the topics containing data received from Motive, using `rviz` , I get the error  ``For frame [mocap]: Fixed Frame [map] does not exist``. This happens for real Motive data as well as for fake data that can be produced with the `natnet-ros package`.

As you can see in the screenshot, I am trying to visualize the `/mocap/rigid_bodies/RaceTracker/pose` topic. Looking on the Internet, it seems like I need a tf topic but I do have it except it cannot be visualized.

Am I using the `rviz` tool wrong or is this a problem with the library? If the latter, how can I help fix it?

**Comment by mje-nz** [comment]
Thanks for the report!

This error means that the tf frame `rviz` is using to visualise the data (`map`) is not being published by anything. You need to set the "Fixed frame" option to a real frame from your system. If all you have running is the `natnet_ros` client, set it to `mocap`.

**Comment by knightsamar** [comment]
That worked. Thank you!
